openapi: 3.1.0
info:
  title: Signal Strength Schemas
  description: Common data structure definitions for measurement and signal strength reporting.
  version: 1.0.0

components:
  schemas:
    BaseMeasureDataModel:
      type: object
      required:
        - latitude
        - longitude
        - timestamp
        - cell_id
        - device_id
        - reported
      properties:
        latitude:
          type: number
          format: double
          description: Geographic latitude coordinate
        longitude:
          type: number
          format: double
          description: Geographic longitude coordinate
        timestamp:
          type: string
          description: When the measurement was taken
        cell_id:
          type: string
          description: Identifier for the cell tower or access point
        device_id:
          type: string
          description: Unique identifier for the reporting device
        reported:
          type: boolean
          description: Flag indicating if the measurement has been reported
      
    SignalStrengthReportModel:
      allOf:
        - $ref: '#/components/schemas/BaseMeasureDataModel'
        - type: object
          required:
            - dbm
            - level_code
          properties:
            dbm:
              type: integer
              description: Signal strength in decibel-milliwatts
            level_code:
              type: integer
              description: Code representing the signal strength level
              
    ConnectivityReportModel:
      allOf:
        - $ref: '#/components/schemas/BaseMeasureDataModel'
        - type: object
          required:
            - upload_speed
            - download_speed
            - ping
            - package_loss
          properties:
            upload_speed:
              type: number
              format: double
              description: Upload speed measurement
            download_speed:
              type: number
              format: double
              description: Download speed measurement
            ping:
              type: number
              format: double
              description: Network latency in milliseconds
            package_loss:
              type: number
              format: double
              description: Packet loss percentage