openapi: 3.1.0
info:
  title: Cellular site
  version: 1.0.0
  description: Site metrics and data

components:
  schemas:
    Site:
      type: object
      required:
        - name
        - latitude
        - longitude
        - status
        - address
      properties:
        name:
          type: string
          description: Name of the site
          example: "Filipino Community Center"
        latitude:
          type: number
          format: double
          description: Geographic latitude coordinate
          example: 47.681932654395915
        longitude:
          type: number
          format: double
          description: Geographic longitude coordinate
          example: -122.31829217664796
        status:
          type: string
          description: Current status of the site
          enum: [active, confirmed, in-conversation]
          example: "active"
        address:
          type: string
          description: Physical address of the site
          example: "5740 Martin Luther King Jr Way S, Seattle, WA 98118"
        cell_id:
          type: array
          description: Optional array of cell identifiers associated with the site
          items:
            type: string
            example: "cell-123"