openapi: 3.1.0
info:
  title: Signal Strength Schemas
  description: Common data structure definitions for measurement and signal strength reporting.
  version: 1.0.0

components:
  schemas:
    LineSummaryItem:
      type: object
      properties:
        site:
          type: string
          description: Name of the site
          example: "Filipino Community Center"
        values:
          type: array
          description: Time series data points for the site
          items:
            type: object
            properties:
              date:
                type: string
                format: date-time
                description: Timestamp for the data point
                example: "2021-01-25T18:00:00.000Z"
              value:
                type: number
                format: double
                description: Average value for the metric at this timestamp
                example: 7.28